CREATE DATABASE BarterPlace;
USE BarterPlace;
CREATE TABLE users(
userID INT PRIMARY KEY AUTO_INCREMENT,
profileName VARCHAR(50) NOT NULL,
contact VARCHAR(50) NOT NULL,
password VARCHAR(25) NOT NULL,
DOB DATE,
state VARCHAR(50) NOT NULL,
city VARCHAR(50) NOT NULL,
address VARCHAR(50) NOT NULL
);

CREATE TABLE posts(
postID INT PRIMARY KEY AUTO_INCREMENT,
userID INT NOT NULL,
postDate DATE NOT NULL,
itemName VARCHAR(50) NOT NULL,
itemDescription VARCHAR(250) NOT NULL,
itemCategory VARCHAR(50) NOT NULL,
postType VARCHAR(10),
postStatus VARCHAR(10) DEFAULT 'current',
FOREIGN KEY (userID) REFERENCES users(userID)
);

